;(function(window,document,setTimeout,$,mw,dev,undefined){'use strict';if(dev.minicomplete!==undefined){mw.log('Error: dev.minicomplete already loaded. Aborting...');return;}dev.minicomplete=(function(){var config=mw.config.get(['wgCanonicalSpecialPageName','wgNamespaceIds','wgScriptPath','wgServer']),global={load:function(){var check,$elem,i,ul;if(arguments.length===0){mw.log('Error: No parameters passed to dev.minicomplete.load');return;}if(arguments.length===1){check=local.elemCheck(arguments[0]);if(check===false){mw.log('Error: No matches for arguments passed to dev.minicomplete.load');return;}$elem=check;}if(arguments.length>1){for(i=0;i<arguments.length;i+=1){check=local.elemCheck(arguments[i]);if(check===false){continue;}else if($elem===undefined){$elem=check;}else{$elem=$elem.add(check);}}if($elem===undefined){mw.log('Error: No matches for arguments passed to dev.minicomplete.load');return;}}if(!document.getElementById('minicomplete-list')){local.insertCSS();ul=document.
createElement('ul');ul.setAttribute('id','minicomplete-list');document.getElementsByTagName('body')[0].appendChild(ul);local.bindEvents();}else{$('#minicomplete-list').hide().empty();}$elem.off('input').on('input',function(){$('#minicomplete-list').hide().empty();local.elem=this;mw.log(this);local.findTerm(this);});}},local={init:function(){if(['Upload','MultipleUpload'].indexOf(config.wgCanonicalSpecialPageName)===-1){return;}mw.loader.implement('minicomplete.dependencies',['/load.php?debug=false&lang=en&mode=articles&skin=oasis&missingCallback=importArticleMissing&articles=u%3Acamtest%3AMediaWiki%3ATextareaHelper.js%7Cu%3Adev%3AColors%2Fcode.js&only=scripts'],{},{});mw.loader.using(['mediawiki.api','minicomplete.dependencies'],function(){global.load('#wpUploadDescription');});},elemCheck:function(elem){if(typeof elem==='string'&&$(elem).length){return $(elem);}if(elem.nodeType&&$(elem).length){return $(elem);}if(elem.jquery&&elem.length){return elem;}mw.log(
'Error: Argument passed to dev.minicomplete.load is not a selector, DOM element of jQuery object');return false;},commentsLoaded:function(){if(window.ArticleComments.initCompleted){mw.log('Article comments loaded');global.load('#article-comm');$($('.article-comm-reply')).on('click',function(){mw.log('reply detected');if($(this).parent().parent().next().find('.wikiaEditor').length){return;}local.editorInserted($('.wikiaEditor').length,'.wikiaEditor');});}else{setTimeout(local.commentsLoaded,500);}},editorInserted:function(editors,selector){if($(selector).length!==editors){mw.log('new editor inserted');global.load(selector);}else{setTimeout(function(){local.editorInserted(editors,selector);},500);}},insertCSS:function(){var page=dev.colors.parse(dev.colors.wikia.page),buttons=dev.colors.parse(dev.colors.wikia.menu),mix=buttons.mix(page,20),shadow=page.lighten(-8),css;if(!page.isBright()){mix=mix.lighten(8);}css=
'#minicomplete-list{position:absolute;z-index:5;display:none;font-size:12px;cursor:pointer;width:245px;margin:0;}'+'#minicomplete-list{border:1px solid $border;background-color:$page;color:$link;-webkit-box-shadow:3px 3px 6px 0 $shadow;box-shadow:3px 3px 6px 0 $shadow;}'+'.minicomplete-option{padding:4px 9px;list-style:none;margin:0;line-height:25px;}'+'.minicomplete-option:hover,.minicomplete-option.selected{background-color:$mix;}';dev.colors.css(css,{mix:mix,shadow:shadow});},bindEvents:function(){$(document).on('keydown',function(e){var $option=$('.minicomplete-option'),$select=$('.minicomplete-option.selected'),i;if(!$option.length){return;}switch(e.keyCode){case 27:case 37:case 39:$('#minicomplete-list').hide().empty();break;case 38:if(!$option.length){return;}e.preventDefault();if(!$select.length){$($option[$option.length-1]).addClass('selected');}else{for(i=0;i<$option.length;i+=1){if($($option[i]).hasClass('selected')){$($option[i]).removeClass('selected');if(i===0){$($option[
$option.length-1]).addClass('selected');}else{$($option[i-1]).addClass('selected');}return;}}}break;case 40:if(!$option.length){return;}e.preventDefault();if(!$select.length){$($option[0]).addClass('selected');}else{for(i=0;i<$option.length;i+=1){if($($option[i]).hasClass('selected')){$($option[i]).removeClass('selected');if(i===($option.length-1)){$($option[0]).addClass('selected');}else{$($option[i+1]).addClass('selected');}return;}}}break;case 13:if(!$select.length){return;}e.preventDefault();local.insertComplete($select.text());break;}});},findTerm:function(elem){if(elem.value===undefined){mw.log('Error: Element does not support value attribute');return;}var searchText=elem.value.substring(0,local.getCaretPos()),linkCheck=searchText.lastIndexOf('[['),templateCheck=searchText.lastIndexOf('{{'),illegalChars=/[\{\}\[\]\|#<>%\+\?\\]/,term,ns;if(!searchText.length){return;}if(linkCheck>-1){if(linkCheck<searchText.lastIndexOf(']]')){return;}if((searchText.length-(linkCheck+2))>=0){term=
searchText.substring(linkCheck+2);if(term.match(illegalChars)){return;}if(term.indexOf(':')===0){term=term.substring(1);}if(!term.length){return;}local.type='[[';local.getSuggestions(term,0);}}if(templateCheck>-1){if(templateCheck<searchText.lastIndexOf('}}')){return;}if((searchText.length-(templateCheck+2))>0){term=searchText.substring(templateCheck+2);if(term.match(illegalChars)){return;}if(term.indexOf(':')===0){term=term.substring(1);ns=0;}else{ns=10;}if(!term.length){return;}local.type='{{';local.getSuggestions(term,ns);}}},getCaretPos:function(){var elem=local.elem,caretPos=0,sel;if(document.selection){elem.focus();sel=document.selection.createRange();sel.moveStart('character',-elem.value.length);caretPos=sel.text.length;}else if(elem.selectionStart||elem.selectionStart==='0'){caretPos=elem.selectionStart;}return(caretPos);},getSuggestions:function(term,ns){var query={action:'query',list:'allpages',aplimit:'5',apfilterredir:'nonredirects',apnamespace:ns,apprefix:term,format:
'json'},termSplit,namespaceId,title;mw.log(term);if(term.indexOf(':')>-1){termSplit=term.split(':');title=termSplit[1];if(termSplit.length>2){return;}namespaceId=config.wgNamespaceIds[termSplit[0].replace(/ /g,'_').toLowerCase()];if(namespaceId){query.apnamespace=namespaceId;query.apprefix=title;}}$.ajax({url:config.wgServer+config.wgScriptPath+'/api.php',data:query,dataType:'json',success:function(data){if(data.error){mw.log('API error: ',data.error.code,data.error.info);return;}if(!data.query.allpages.length){return;}local.showSuggestions(data.query.allpages);},error:function(xhr,error,desc){mw.log('AJAX error: ',error,' - ',desc);}});},showSuggestions:function(result){var options='',$body=$('body').width(),i,coords,offset,$list,leftpos,$options;mw.log(result);for(i=0;i<result.length;i+=1){options+='<li class="minicomplete-option">'+result[i].title+'</li>';}$('#minicomplete-list').html(options);$list=$('#minicomplete-list');$list.show();coords=$(local.elem).textareaHelper('caretPos')
;offset=$(local.elem).offset();leftpos=offset.left+coords.left;if(leftpos+$list.width()>$body){leftpos=$body-$list.width();}$list.css({top:offset.top+coords.top-$list.height(),left:leftpos});$options=$('.minicomplete-option');$options.on('click',function(){local.insertComplete($(this).text());});$options.on('mouseover',function(){if($('.minicomplete-option.selected').length){$options.removeClass('selected');}});},insertComplete:function(complete){var caret=local.getCaretPos(),val=local.elem.value,text=val.substring(0,caret),open=local.type,close=open==='[['?']]':'}}',before=text.substring(0,text.lastIndexOf(open));if(open==='{{'&&complete.split(':')[0]==='Template'){complete=complete.split(':')[1];}if(text[text.lastIndexOf(open)+2]===':'){open+=':';}local.elem.value=before+open+complete+close+val.substring(caret);$('#minicomplete-list').hide().empty();}};return global;}());}(this,this.document,this.setTimeout,this.jQuery,this.mediaWiki,this.dev=this.dev||{}));;$('.cioCompareLink').each
(function(){var props=($(this).attr('title')||'').split('|'),linkText=(props[0]!=='')?props[0]:'Compare items',items=(props.length>=2)?props.slice(1):[mw.config.get('wgPageName')],$link=$('<a>').attr({href:'#',title:'Compare this item with other items.'}).click(function(e){e.preventDefault();cioOpen(items);}).text(linkText);$(this).empty().append($link);});var $cioImgDelete=$('<img>').attr({src:'http://img200.imageshack.us/img200/7898/transdelrow.png',width:14,height:13,alt:'[X]'}),$cioImgLoading=$('<img>').attr({src:mw.config.get('stylepath')+'/common/progress-wheel.gif',width:16,height:16,alt:'...'}),$cioImgError=$('<img>').attr({src:'http://img12.imageshack.us/img12/508/1248624996error.png',width:16,height:16,alt:'!!'});function cioOpen(items){if(!$('#overlay').length){$('<div>').attr('id','overlay').appendTo('body').show().unbind('click').click(cioClose);}else{$('#overlay').show().unbind('click').click(cioClose);}$(document).keydown(function(e){if(e.which==27){cioClose();}});var
html=' \
<div id="cioTitle"> \
 <div id="modalClose" onclick="cioClose();" title="Close this overlay."><img src="http://img693.imageshack.us/img693/9906/closes.png" width="48" height="24" alt="[X]" /></div> \
 Compare Items \
</div> \
<form name="cioCompare" id="cioCompare" onsubmit="cioSubmit(this.cioItem.value); return false;" action="#"> \
    <table> \
        <tr> \
            <td><label for="cioItem">Compare <b>'+mw.config.get('wgTitle')+
'</b> with:</label></td> \
            <td><input type="input" type="text" name="cioItem" id="cioItem" value="" /> <input type="submit" value="Add" /></td> \
        </tr> \
        <tr> \
            <td>&nbsp;</td> \
            <td id="cioStatus"></td> \
        </tr> \
    </table> \
</form> \
<table class="wikitable" id="cioItems"> \
    <thead> \
        <tr> \
            <th rowspan="2">Name</th> \
                <th colspan="3">Mainhand Info</th> \
                <th colspan="3">Offhand Info</th> \
                <th colspan="3">Attributes</th> \
                <th colspan="3"><span style="font-size:80%">Critical Bonuses</span></th> \
                <th width="30">Speed</th> \
                <th width="30">Weight</th> \
            <th width="30">GE</th> \
        </tr> \
        <tr> \
            <th width="35">Style</th> \
            <th width="35"><span style="font-size:80%">Damage</span></th> \
            <th width="35"><span style="font-size:80%">Accuracy</span></th> \
            <th width="35">Style</th> \
            <th width="35"><span style="font-size:80%">Damage</span></th> \
            <th width="35"><span style="font-size:80%">Accuracy</span></th> \
            <th width="35" title="Armour rating"><img src="http://images3.wikia.nocookie.net/runescape/images/thumb/d/d8/Defence-icon.png/18px-Defence-icon.png"" alt="Arm" /></th> \
            <th width="35" title="Life bonus"><img src="http://images3.wikia.nocookie.net/runescape/images/thumb/1/1d/Constitution-icon.png/21px-Constitution-icon.png" alt="Lif" /></th> \
            <th width="35" title="Prayer bonus"><img src="http://images4.wikia.nocookie.net/runescape/images/2/24/Prayer-icon.png" width="20" height="20" alt="Pra" /></th> \
            <th width="35" title="Melee critical"><img src="http://images1.wikia.nocookie.net/runescape/images/9/90/Stab_Attack_Style.png" width="11" height="20" alt="Dam" /></th> \
            <th width="35" title="Ranged critical"><img src="http://images3.wikia.nocookie.net/runescape/images/7/72/Ranged-icon.png" width="20" height="20" alt="Rng" /></th> \
            <th width="35" title="Magic critical"><img src="http://images2.wikia.nocookie.net/runescape/images/7/77/Magic-icon.png" width="20" height="19" alt="Mag" /></th> \
            <th title="Speed"><img src="http://images2.wikia.nocookie.net/runescape/images/a/a9/Energy.png" width="17" height="20" alt="Spd" /></th> \
            <th title="Weight (kg)"><img src="http://images4.wikia.nocookie.net/runescape/images/f/fc/Weight-icon.png" width="20" height="20" alt="Wgt" /></th> \
            <th title="Grand Exchange Price"><img src="http://images3.wikia.nocookie.net/runescape/images/6/65/Coins_25.png" width="20" height="15" alt="GE" /></th> \
        </tr> \
    </thead> \
    <tbody> \
        <tr id="cioTotals"> \
        </tr> \
    </tbody> \
</table>'
;$('<div />').html(html).attr('id','modal').appendTo('body');$('#modal').css('left',$(window).width()/2-($('#modal').width()/2));for(var i=0;i<items.length&&i<5;i++){cioSubmit(items[i]);}}function cioClose(){$('#modal').fadeOut('normal',function(){$('#modal').remove();$('#overlay').hide();});$(document).unbind('keydown');}function cioSubmit(itemName){function addCommas(nStr){nStr+='';x=nStr.split('.');x1=x[0];x2=x.length>1?'.'+x[1]:'';var rgx=/(\d+)(\d{3})/;while(rgx.test(x1)){x1=x1.replace(rgx,'$1'+','+'$2');}return x1+x2;}function calcTotals(){var totals=[];for(var i=0;i<15;i++){totals[i]=0;}$('#cioItems tbody tr').not('#cioTotals').each(function(){var i=0;$(this).children('td').each(function(){var num=$(this).text().replace(/,/g,'');totals[i++]+=(isNaN(num)?0:parseInt(num));});});$('#cioTotals').empty().append($('<th />').text('Total'));for(var i in totals){$('#cioTotals').append(format((/(1?2|5)/.test(i))?null:(addCommas(totals[i])+'')));}}function format(str){if(str==null||
/no|^\s*<!--.*-->\s$/i.test(str)){return $('<td />').attr('class','cioEmpty').text('--');}else{str=str.replace(/<!--.*?-->/g);if(/\d/.test(str.substring(0,1))){str='+'+str;}if(/\w/.test(str.substring(0,1)))return $('<td />').text(str);else return $('<td />').attr('class',(str.substring(0,1)=='-')?'cioNeg':'cioPos').text(str);}}function parseTemplate(text,tpl){tpl=tpl.replace(/[_ ]/g,'[_ ]');var re=new RegExp('{{\\s*(template:)?'+tpl+'\\s*\\|([\\w\\W]+?[^!])}}','gi');var data=[];var match;while(match=re.exec(text)){var params=match[2].split('|');var j=1;var tplData=[];for(var k in params){var t=params[k].split('=');var name=null;var value=null;if(t.length==1){name=(j++)+'';value=t[0];}else{name=t[0];value=t[1];}tplData[$.trim(name)]=$.trim(value);}data.push(tplData);}return data;}function showError(str){$('#cioStatus').empty().attr('class','cioError').append($cioImgError.clone()).append(' '+str);}function ajaxError(xhr,error){showError('Error: '+error);}function ajaxSuccess(data){var
bonusCols=['astab','aslash','acrush','amagic','arange','dstab','dslash','dcrush','dmagic','drange','slot','str','prayer',];var pages=data.query.pages,exchangePageId=null,pageId=null;for(var i in pages){if(pages[i].ns=='112'){exchangePageId=pages[i].pageid;}else{pageId=pages[i].pageid;}}if(pageId==null){showError('Could not find that item.');}else{var page=data.query.pages[pageId],exchangePage=data.query.pages[exchangePageId],pageTitle=page.title,pageContent=page.revisions[0]['*'],bonusData=parseTemplate(pageContent,'infobox bonuses'),itemData=parseTemplate(pageContent,'infobox item'),exchangeData=[];if(exchangePage){var exchangeContent=exchangePage.revisions[0]['*'].replace('{{{View}}}','');exchangeData=parseTemplate(exchangeContent,'exchangeitem');}for(var i in bonusData){var $row=$('<tr>'),$th=$('<th>'),$delLink=$('<a>').attr({href:'#',title:'Remove this row.'}).click(function(){$(this).closest('tr').fadeOut('slow',function(){$(this).remove();calcTotals();});}),$itemLink=$('<a>').
attr({href:mw.config.get('wgArticlePath').replace('$1',encodeURI(pageTitle)),title:pageTitle}).text(pageTitle);$delLink.append($cioImgDelete.clone());$th.append($delLink).append(' ').append($itemLink);$row.append($th);for(var j in bonusCols){$row.append(format(bonusData[i][bonusCols[j]]));}$row.append(format(itemData.length?itemData[0]['weight']:null));$row.append(format(exchangeData.length?exchangeData[0]['Price']:null));$('#cioTotals').before($row);}if(!bonusData.length){showError('No bonus data found for the item.');}else{calcTotals();$('#cioStatus').empty();}}}$('#cioStatus').empty().attr('class','cioLoading').append($cioImgLoading.clone()).append(' Loading...');$.ajax({data:{'action':'query','prop':'revisions','titles':itemName+'|Exchange:'+itemName,'rvprop':'content','redirects':'','format':'json'},dataType:'json',success:ajaxSuccess,error:ajaxError,url:mw.config.get('wgScriptPath')+'/api.php',timeout:10000});};jQuery(function($){"use strict";$('.changePageTitle').eq(0).each(
function(){var $h1=$('.WikiaPageHeader h1, h1#firstHeading').eq(0);$h1.prop('title',$h1.text()).empty().append(this.childNodes);}).end().remove();});;;(function($,document){'use strict';function injectVideo(){var tags=$('.youtube'),i,contents,iframe;if(tags.length===0){return;}for(i=0;i<tags.length;i+=1){contents=$(tags[i]).html().split('|');if(contents[0]==='ERROR'){return;}iframe=document.createElement('iframe');iframe.src='http://www.youtube.com/embed/'+contents[0];iframe.height=contents[1];iframe.width=contents[2];$(tags[i]).html(iframe);$(tags[i]).show();}$('.original-link').hide();}$(function(){injectVideo();});}(this.jQuery,this.document));;(function($,mw){'use strict';function addRSWGuideModule(){$('<section>').attr('class','RSWGuide module').append($('<h1>').css({'margin-top':'0px','margin-bottom':'10px'}).text('Are advertisements obstructing this page?')).append($('<div>').append($('<p>').append($('<a>').attr('href','/wiki/2007scape_Wiki:Advertisements').text(
'Click here to find out how to resolve that'),'.'))).insertBefore('.LatestPhotosModule');}function init(){if($(".LatestPhotosModule").length){addRSWGuideModule();return;}setTimeout(init,500);}init()}(this.jQuery,this.mediaWiki));;;mw.loader.state({"wikia.fake.articles.54e68dbf2577d515f82533cfa9a63f0e":"ready"});

/* cache key: 2007scape:resourceloader:filter:minify-js:7:909a04cf4444ccfcb58f0ed5c238c00d */